language: java

services:
  - mysql

before_script:
- mysql -u root -e 'GRANT ALL ON *.* TO 'root'@'localhost';'

test:
- mysql -u root -p root -e 'GRANT ALL ON *.* TO 'root'@'localhost';'
  dist:precise
